language: node_js
dist: trusty
node_js:
  - 'node'

before_install:
  - cd website

script:
  - ls
  - node_modules/webpack/webpack.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: website/build
  on:
    branch: master