language: node_js
dist: trusty
node_js:
  - 'node'

before_install:
  - cd website

script:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master