language: node_js

script:
  - cd website
  - node_modules/webpack/webpack.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: website/build
  on:
    branch: master